# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruitname', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Fruits',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
    ]
